# Generated by Django 5.2.4 on 2025-07-07 16:28

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логін')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Емейл')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активний')),
                ('language', models.CharField(choices=[('en', 'EN'), ('uk', 'UK')], default='en', max_length=2, verbose_name='Мова')),
                ('type', models.CharField(choices=[('user', 'Користувач'), ('carrier', 'Перевізник')], default='user', max_length=10, verbose_name='Тип')),
                ('two_factor_auth', models.BooleanField(default=False, verbose_name='Двоетапна аутентифікація')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('from_city', models.CharField(max_length=100, verbose_name='Місто відправлення')),
                ('to_city', models.CharField(max_length=100, verbose_name='Місто прибуття')),
                ('date_and_time', models.JSONField(verbose_name='Дата і час поїздки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.user', verbose_name='Власник туру')),
            ],
            options={
                'verbose_name': 'Путівка',
                'verbose_name_plural': 'Путівки',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(verbose_name='Місце в автобусі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.travels', verbose_name='Путівка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.user', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
            },
        ),
    ]
