# Generated by Django 5.1.5 on 2025-07-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_user_two_factor_code_user_two_factor_code_expires_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Українська')], default='en', max_length=2, verbose_name='Language'),
        ),
    ]
