# Generated by Django 5.1.5 on 2025-07-17 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_alter_user_options_alter_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_code_expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code_expires',
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен підтвердження')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('expires_at', models.DateTimeField(verbose_name='Дата закінчення дії токена')),
                ('is_used', models.BooleanField(default=False, verbose_name='Використаний')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Підтвердження email',
                'verbose_name_plural': 'Підтвердження email',
            },
        ),
    ]
