# Generated by Django 5.1.5 on 2025-07-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_remove_user_two_factor_code_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Підтвердження email', 'verbose_name_plural': 'Підтвердження email'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Квиток', 'verbose_name_plural': 'Квитки'},
        ),
        migrations.AlterModelOptions(
            name='travels',
            options={'ordering': ['-created_at'], 'verbose_name': 'Путівка', 'verbose_name_plural': 'Путівки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата запиту на видалення акаунту'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='2FA код'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_code_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час закінчення дії 2FA'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.CharField(max_length=128, unique=True, verbose_name='Токен підтвердження'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='date_and_time',
            field=models.JSONField(help_text='Format example: {"2025-07-25": ["09:00", "14:00"]}', verbose_name='Дата і час поїздки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True, verbose_name='Емейл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', related_query_name='custom_user', to='auth.permission', verbose_name='User permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='Логін'),
        ),
    ]
