# Generated by Django 5.1.5 on 2025-07-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_alter_emailverification_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата запланованого видалення'),
        ),
    ]
