# Generated by Django 5.1.5 on 2025-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_alter_user_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(db_index=True, verbose_name='Дата закінчення дії токена'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('travel', 'place'), name='unique_travel_place'),
        ),
    ]
